language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket

  matrix:
    - RACKET_VERSION=7.2
    - RACKET_VERSION=7.3
    # "HEAD" is a daily snapshot built from the `master` branch.
    # This is the main variant of Racket that uses its own runtime.
    - RACKET_VERSION=HEAD
    # "HEADCS" is a daily snapshot built from the `master` branch.
    # This is an experimental variant of Racket that uses Chez Scheme.
    - RACKET_VERSION=HEADCS
    # "RELEASE" is a release candidate that updates only during the
    # weeks before a new release. The final release candidate should
    # remain available until the next release cycle. As a result, you
    # may leave this in your .travis.yml all the time. See:
    # <https://pre-release.racket-lang.org/>.
    - RACKET_VERSION=RELEASE

matrix:
    # You may want to test against certain versions of Racket, without
  # having them count against the overall success/failure. For example
  # here we include the development versions:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE
  # Fast finish: Overall build result is determined as soon as any of
  # its rows have failed, or, all of its rows that aren't allowed to
  # fail have succeeded.
  fast_finish: true

  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto -n graphite

script:
  - raco test --package graphite
  - raco exe graphite/graphite.rkt

after_success:
  - scribble --dest-name index.html --dest scribble-docs graphite/graphite.scrbl

deploy:
  provider: pages
  local_dir: scribble-docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
